spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tutorials-comments
    username: root
    password:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop